/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;

/**
 *
 * @author DELL
 */
public class Impresion extends javax.swing.JPanel implements Printable  {

    /**
     * Creates new form Impresion
     */
    public Impresion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNumeroCo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        txtBebidas = new javax.swing.JLabel();
        txtExtras = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jltEntradas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlsPlatos = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel1.setText("--------------------DON PIMENTON--------------------");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 57, -1, 14));

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel9.setText("Av . Micaela con retablo Condominios Vista Sol");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 77, -1, -1));

        txtNumeroCo.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txtNumeroCo.setText("N° Comanda");
        jPanel3.add(txtNumeroCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, 110, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel11.setText("Numero celular:                            914 515 407");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 98, -1, -1));

        txtTotal.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        txtTotal.setText("Total");
        jPanel3.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txtDireccion.setText("Direccion");
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        txtDescripcion.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txtDescripcion.setText("Descripcion");
        jPanel3.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        txtBebidas.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txtBebidas.setText("Bebidas");
        jPanel3.add(txtBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        txtExtras.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txtExtras.setText("Extras");
        jPanel3.add(txtExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jltEntradas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jltEntradas.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(jltEntradas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 160));

        jlsPlatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlsPlatos.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jScrollPane4.setViewportView(jlsPlatos);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 190, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JList<String> jlsPlatos;
    public javax.swing.JList<String> jltEntradas;
    public javax.swing.JLabel txtBebidas;
    public javax.swing.JLabel txtDescripcion;
    public javax.swing.JLabel txtDireccion;
    public javax.swing.JLabel txtExtras;
    public javax.swing.JLabel txtNumeroCo;
    public javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {if (pageIndex == 0) {
            Graphics2D graphics2d = (Graphics2D) graphics;
            graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            printAll(graphics2d);
            return PAGE_EXISTS;
        }else{
            return NO_SUCH_PAGE;
        }
    }
}
