package Vista;

import Clases.Comandas;
import Clases.PrecioPlatos;
import Clases.RegistroComandasDAO;
import Controladores.ControladorRegistroComanda;
import Vista.MenuSeleccion;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class RegistrarComandas extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;
    Comandas coman = new Comandas();
    RegistroComandasDAO comanDAO = new RegistroComandasDAO();
    
    public RegistrarComandas() {
        initComponents();
        modelo= (DefaultTableModel)tblListado_RegistrarComanda.getModel();
        txtFecha.setText(fecha());
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        ControladorRegistroComanda conRegisComan = new ControladorRegistroComanda(coman, comanDAO, this);
    }

    public static String fecha() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtComanda_RegistrarComanda = new javax.swing.JTextField();
        txtNombre_RegistrarComanda = new javax.swing.JTextField();
        txtCantEntradas_RegistrarComanda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion_RegistrarComanda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescrip_RegistrarComanda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCantPlatos_RegistrarComanda = new javax.swing.JTextField();
        txtCantBebidas_RegistrarComanda = new javax.swing.JTextField();
        cbxPlato_RegistrarComanda = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxEntrada_RegistrarComanda = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxBebidas_RegistrarComanda = new javax.swing.JComboBox<>();
        btnLimpiar_RegistrarComandas = new javax.swing.JButton();
        btnMostrar_RegistarComandas = new javax.swing.JButton();
        txtFecha = new javax.swing.JLabel();
        btnModificar_RegistrarComanda = new javax.swing.JButton();
        txtBuscar_RegistrarComanda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblListado_RegistrarComanda = new javax.swing.JTable();
        txtID_RegistrarComanda = new javax.swing.JTextField();

        setBackground(new java.awt.Color(27, 27, 27));
        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(27, 27, 27));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jPanel2.setBackground(new java.awt.Color(27, 27, 27));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("N° Comanda:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cantidad de Bebidas:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        txtComanda_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        txtComanda_RegistrarComanda.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtComanda_RegistrarComanda.setForeground(new java.awt.Color(255, 255, 255));
        txtComanda_RegistrarComanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtComanda_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 40, 20));

        txtNombre_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        txtNombre_RegistrarComanda.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtNombre_RegistrarComanda.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre_RegistrarComanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        txtNombre_RegistrarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_RegistrarComandaActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, 20));

        txtCantEntradas_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        txtCantEntradas_RegistrarComanda.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtCantEntradas_RegistrarComanda.setForeground(new java.awt.Color(255, 255, 255));
        txtCantEntradas_RegistrarComanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtCantEntradas_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 40, 20));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        txtDireccion_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        txtDireccion_RegistrarComanda.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtDireccion_RegistrarComanda.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion_RegistrarComanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtDireccion_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 170, 20));

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descripcion:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtDescrip_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        txtDescrip_RegistrarComanda.setForeground(new java.awt.Color(255, 255, 255));
        txtDescrip_RegistrarComanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtDescrip_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 370, 20));

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cantidad Entradas:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cantidad de Platos:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtCantPlatos_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        txtCantPlatos_RegistrarComanda.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtCantPlatos_RegistrarComanda.setForeground(new java.awt.Color(255, 255, 255));
        txtCantPlatos_RegistrarComanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtCantPlatos_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 40, 20));

        txtCantBebidas_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        txtCantBebidas_RegistrarComanda.setForeground(new java.awt.Color(255, 255, 255));
        txtCantBebidas_RegistrarComanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtCantBebidas_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 40, 20));

        cbxPlato_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        cbxPlato_RegistrarComanda.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        cbxPlato_RegistrarComanda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---", "Arroz con pollo", "Salchipapa clasica", "Arroz a la cubana", "Tortilla de verduras", "Pescado frito", "Higado a la plancha", "Pollada", "Aji de gallina", "Suprema de pollo", "Adobo de pollo", "Milanesa de pollo  con papas fritas", "Mondonguito a la italiana", "Tallarines verdes con filete de pollo", "Picante de carne con platano", "Estofado de pollo", "Asado de carne con pure de papas", "Pollo al horno con ensalada rusa", "Arroz con chancho", "Olluquito a lo pobre", "Pollo a la norteña con frejoles" }));
        jPanel2.add(cbxPlato_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Plato de Fondo:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Entrada:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        cbxEntrada_RegistrarComanda.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        cbxEntrada_RegistrarComanda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---", "Tequeños", "Crema de rocoto", "Ensalada fresca", "Sopa de Morón", "Papa a la huancaina", "Bolicausas con huancaina", "Cazuela de pollo", "Ceviche", "Sopa de aguadito" }));
        cbxEntrada_RegistrarComanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(cbxEntrada_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 240, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bebidas:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        cbxBebidas_RegistrarComanda.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        cbxBebidas_RegistrarComanda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---", "Coca cola 500ml", "Inca cola 500ml", "Pepsi 500ml", "Sin Bebida" }));
        cbxBebidas_RegistrarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBebidas_RegistrarComandaActionPerformed(evt);
            }
        });
        jPanel2.add(cbxBebidas_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 240, -1));

        btnLimpiar_RegistrarComandas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        btnLimpiar_RegistrarComandas.setContentAreaFilled(false);
        btnLimpiar_RegistrarComandas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar-Gris.png"))); // NOI18N
        btnLimpiar_RegistrarComandas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar-Negro.png"))); // NOI18N
        btnLimpiar_RegistrarComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar_RegistrarComandasActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar_RegistrarComandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 80, 40));

        btnMostrar_RegistarComandas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        btnMostrar_RegistarComandas.setContentAreaFilled(false);
        btnMostrar_RegistarComandas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar-Gris.png"))); // NOI18N
        btnMostrar_RegistarComandas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar-Negro.png"))); // NOI18N
        btnMostrar_RegistarComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrar_RegistarComandasActionPerformed(evt);
            }
        });
        jPanel2.add(btnMostrar_RegistarComandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 80, 40));

        txtFecha.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(27, 27, 27));
        txtFecha.setText("DD/MM/YYYY");
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        btnModificar_RegistrarComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnModificar_RegistrarComanda.setContentAreaFilled(false);
        btnModificar_RegistrarComanda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar-Gris.png"))); // NOI18N
        btnModificar_RegistrarComanda.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar-Negro.png"))); // NOI18N
        jPanel2.add(btnModificar_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 80, 40));

        txtBuscar_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        txtBuscar_RegistrarComanda.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtBuscar_RegistrarComanda.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar_RegistrarComanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        txtBuscar_RegistrarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar_RegistrarComandaActionPerformed(evt);
            }
        });
        jPanel2.add(txtBuscar_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 60, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("por comanda");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        tblListado_RegistrarComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Comanda", "N° Comanda", "Nombre", "Direccion", "Cant. Entradas", "Entrada", "Cant. Platos", "Platos", "Cant. Bebidas", "Bebidas", "Descripcion"
            }
        ));
        tblListado_RegistrarComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListado_RegistrarComandaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblListado_RegistrarComanda);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 850, 270));

        txtID_RegistrarComanda.setBackground(new java.awt.Color(27, 27, 27));
        txtID_RegistrarComanda.setForeground(new java.awt.Color(255, 255, 255));
        txtID_RegistrarComanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtID_RegistrarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 40, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombre_RegistrarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_RegistrarComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_RegistrarComandaActionPerformed

    private void cbxBebidas_RegistrarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBebidas_RegistrarComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBebidas_RegistrarComandaActionPerformed

    private void btnLimpiar_RegistrarComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar_RegistrarComandasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiar_RegistrarComandasActionPerformed

    private void btnMostrar_RegistarComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrar_RegistarComandasActionPerformed
      
    }//GEN-LAST:event_btnMostrar_RegistarComandasActionPerformed

    private void txtBuscar_RegistrarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar_RegistrarComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar_RegistrarComandaActionPerformed

    private void tblListado_RegistrarComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListado_RegistrarComandaMouseClicked
        if (evt.getSource() == tblListado_RegistrarComanda) {
            int fila = tblListado_RegistrarComanda.rowAtPoint(evt.getPoint());
            txtID_RegistrarComanda.setText(tblListado_RegistrarComanda.getValueAt(fila, 0).toString());
            txtComanda_RegistrarComanda.setText(tblListado_RegistrarComanda.getValueAt(fila, 1).toString());
            txtNombre_RegistrarComanda.setText(tblListado_RegistrarComanda.getValueAt(fila, 2).toString());
            txtDireccion_RegistrarComanda.setText(tblListado_RegistrarComanda.getValueAt(fila, 3).toString());
            txtCantEntradas_RegistrarComanda.setText(tblListado_RegistrarComanda.getValueAt(fila, 4).toString());
            cbxEntrada_RegistrarComanda.setSelectedItem(tblListado_RegistrarComanda.getValueAt(fila, 5).toString());
            txtCantPlatos_RegistrarComanda.setText(tblListado_RegistrarComanda.getValueAt(fila, 6).toString());
            cbxPlato_RegistrarComanda.setSelectedItem(tblListado_RegistrarComanda.getValueAt(fila, 7).toString());
            txtCantBebidas_RegistrarComanda.setText(tblListado_RegistrarComanda.getValueAt(fila, 8).toString());
            cbxBebidas_RegistrarComanda.setSelectedItem(tblListado_RegistrarComanda.getValueAt(fila, 9).toString());
            txtDescrip_RegistrarComanda.setText(tblListado_RegistrarComanda.getValueAt(fila, 10).toString());
        }
    }//GEN-LAST:event_tblListado_RegistrarComandaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLimpiar_RegistrarComandas;
    public javax.swing.JButton btnModificar_RegistrarComanda;
    public javax.swing.JButton btnMostrar_RegistarComandas;
    public javax.swing.JComboBox<String> cbxBebidas_RegistrarComanda;
    public javax.swing.JComboBox<String> cbxEntrada_RegistrarComanda;
    public javax.swing.JComboBox<String> cbxPlato_RegistrarComanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable tblListado_RegistrarComanda;
    public javax.swing.JTextField txtBuscar_RegistrarComanda;
    public javax.swing.JTextField txtCantBebidas_RegistrarComanda;
    public javax.swing.JTextField txtCantEntradas_RegistrarComanda;
    public javax.swing.JTextField txtCantPlatos_RegistrarComanda;
    public javax.swing.JTextField txtComanda_RegistrarComanda;
    public javax.swing.JTextField txtDescrip_RegistrarComanda;
    public javax.swing.JTextField txtDireccion_RegistrarComanda;
    private javax.swing.JLabel txtFecha;
    public javax.swing.JTextField txtID_RegistrarComanda;
    public javax.swing.JTextField txtNombre_RegistrarComanda;
    // End of variables declaration//GEN-END:variables
}
