/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Cliente;
import Clases.ClienteDAO;
import Controladores.ControladorCliente;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class RegistroClientes extends javax.swing.JInternalFrame {

     DefaultTableModel modelo;
     Cliente cl = new Cliente();
     ClienteDAO clDAO = new ClienteDAO();
     
    public RegistroClientes() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        ControladorCliente cc = new ControladorCliente(cl, clDAO, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDIRECCION = new javax.swing.JTextField();
        txtBUSCAR = new javax.swing.JTextField();
        btnAGREGAR = new javax.swing.JButton();
        btnMODIFICAR = new javax.swing.JButton();
        btnLIMPIAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDATOS_REGISTROCLIENTES = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTELEFONO = new javax.swing.JTextField();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 27, 27));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jPanel2.setBackground(new java.awt.Color(27, 27, 27));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 82, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Direccion:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 38, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 82, -1, -1));

        txtId.setBackground(new java.awt.Color(27, 27, 27));
        txtId.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        txtId.setEnabled(false);
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, -1));

        txtNombre.setBackground(new java.awt.Color(27, 27, 27));
        txtNombre.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 80, 162, -1));

        txtDIRECCION.setBackground(new java.awt.Color(27, 27, 27));
        txtDIRECCION.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtDIRECCION.setForeground(new java.awt.Color(255, 255, 255));
        txtDIRECCION.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtDIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 36, 162, -1));

        txtBUSCAR.setBackground(new java.awt.Color(27, 27, 27));
        txtBUSCAR.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtBUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        txtBUSCAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 50, -1));

        btnAGREGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnAGREGAR.setContentAreaFilled(false);
        btnAGREGAR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar-Gris.png"))); // NOI18N
        btnAGREGAR.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar-Negro.png"))); // NOI18N
        btnAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAGREGARActionPerformed(evt);
            }
        });
        jPanel2.add(btnAGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 80, 30));

        btnMODIFICAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btnMODIFICAR.setContentAreaFilled(false);
        btnMODIFICAR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar-Gris.png"))); // NOI18N
        btnMODIFICAR.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar-Negro.png"))); // NOI18N
        jPanel2.add(btnMODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 80, 30));

        btnLIMPIAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        btnLIMPIAR.setContentAreaFilled(false);
        btnLIMPIAR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar-Gris.png"))); // NOI18N
        btnLIMPIAR.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar-Negro.png"))); // NOI18N
        jPanel2.add(btnLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 80, 30));

        tblDATOS_REGISTROCLIENTES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Direccion", "Telefono"
            }
        ));
        tblDATOS_REGISTROCLIENTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDATOS_REGISTROCLIENTESMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDATOS_REGISTROCLIENTES);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 840, 300));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 38, -1, -1));

        txtTELEFONO.setBackground(new java.awt.Color(27, 27, 27));
        txtTELEFONO.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtTELEFONO.setForeground(new java.awt.Color(255, 255, 255));
        txtTELEFONO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.add(txtTELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 162, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAGREGARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAGREGARActionPerformed

    private void tblDATOS_REGISTROCLIENTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDATOS_REGISTROCLIENTESMouseClicked
        if (evt.getSource() == tblDATOS_REGISTROCLIENTES) {
            int fila = tblDATOS_REGISTROCLIENTES.rowAtPoint(evt.getPoint());
            txtId.setText(tblDATOS_REGISTROCLIENTES.getValueAt(fila, 0).toString());
            txtNombre.setText(tblDATOS_REGISTROCLIENTES.getValueAt(fila, 1).toString());
            txtDIRECCION.setText(tblDATOS_REGISTROCLIENTES.getValueAt(fila, 2).toString());
            txtTELEFONO.setText(tblDATOS_REGISTROCLIENTES.getValueAt(fila, 3).toString());  
        }  
    }//GEN-LAST:event_tblDATOS_REGISTROCLIENTESMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAGREGAR;
    public javax.swing.JButton btnLIMPIAR;
    public javax.swing.JButton btnMODIFICAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblDATOS_REGISTROCLIENTES;
    public javax.swing.JTextField txtBUSCAR;
    public javax.swing.JTextField txtDIRECCION;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTELEFONO;
    // End of variables declaration//GEN-END:variables
}
